language: python
python:
- '3.5'
before install:
- echo "$PATH"
install:
- pip3.5 install coveralls
- pip install nosetests
- pip3.5 install -r requirements.txt
script:
- python3.5 setup.py install
- coverage run tests/test_riboSelect.py
- nosetests --with-coverage tests/
after_success: coveralls
deploy:
  provider: pypi
 #server: https://mypackageindex.com/index
  user: NickWaters
  password: itsablunderfullife
  on:
    tags: true
