language: python
os:
- linux
python:
- '3.5'
- '3.6'
before install:
- echo "$PATH"
install:
- pip install coveralls
- pip install -r requirements.txt
- "./install_tools.sh"
- "./debug_travis.sh"
script:
- python setup.py install
- nosetests --with-coverage --cover-package=riboSeed tests/
after_success: coveralls
deploy:
  provider: pypi
 #server: https://mypackageindex.com/index
  user: NickWaters
  password: itsablunderfullife
  on:
    tags: true
